# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20171106_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Song'),
        ),
    ]
